version: '3.9'

services:
#Server connection: 127.0.0.1\mssql-server,1434
#User: sa
#Pass: !123456Aab

  mssql-server: 
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    hostname: dfd-sql
    user: '0:0'
    environment:
      SA_PASSWORD: '!123456Aab'
      MSSQL_SA_PASSWORD: '!123456Aab'
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1434:1433"   # Map container port 1433 to host port 1434
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.5'    # Limit to 0.5 CPU core
          memory: 2G   # Limit to 512MB memory

  mongodb: # Conn: mongodb://localhost:27018
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"  # Map container port 27017 to host port 27018
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.5'    # Limit to 0.5 CPU core
          memory: 2G   # Limit to 512MB memory

networks:
  backend:

volumes:
  mssql_data:
  mongodb_data:
