
ALTER TABLE SongArtists DROP CONSTRAINT fk_SongArtists_ArtistId_Songs;
ALTER TABLE Songs DROP CONSTRAINT PK__Songs__3214EC0754705CDE;
GO

ALTER TABLE SongArtists
DROP COLUMN PartitionID
GO

CREATE CLUSTERED INDEX DUMMY_INDEX ON Songs(Id, TrendId) ON [PRIMARY]
DROP PARTITION SCHEME ps_Song_trends
DROP PARTITION FUNCTION pf_Song_trends
GO

DROP INDEX DUMMY_INDEX ON Songs;
GO

ALTER DATABASE SpotifyDataset
REMOVE FILE MOVE_DOWN
ALTER DATABASE SpotifyDataset
REMOVE FILE MOVE_UP
ALTER DATABASE SpotifyDataset
REMOVE FILE NEW_ENTRY
ALTER DATABASE SpotifyDataset
REMOVE FILE SAME_POSITION
ALTER DATABASE SpotifyDataset
REMOVE FILE NULL_POSITION
GO

ALTER DATABASE SpotifyDataset
REMOVE FILEGROUP MOVE_DOWN
ALTER DATABASE SpotifyDataset
REMOVE FILEGROUP MOVE_UP
ALTER DATABASE SpotifyDataset
REMOVE FILEGROUP NEW_ENTRY
ALTER DATABASE SpotifyDataset
REMOVE FILEGROUP SAME_POSITION
ALTER DATABASE SpotifyDataset
REMOVE FILEGROUP NULL_POSITION
GO

ALTER TABLE Songs ADD CONSTRAINT PK__Songs__3214EC0754705CDE PRIMARY KEY CLUSTERED (Id) GO
ALTER TABLE SongArtists ADD CONSTRAINT fk_SongArtists_ArtistId_Songs FOREIGN KEY (SongId) REFERENCES [SpotifyDataset].[dbo].Songs (Id)
GO

BACKUP LOG SpotifyDataset
TO DISK = '/var/opt/mssql/data/log'
GO
