DROP INDEX IF EXISTS IX_Artists_artist ON Artists
CREATE INDEX IX_Artists_artist ON Artists (artist)
GO

DROP INDEX IF EXISTS IX_SongArtists_ArtistId ON SongArtists
CREATE INDEX IX_SongArtists_ArtistId ON SongArtists (ArtistId)
GO

DROP INDEX IF EXISTS IX_SongArtists_SongId ON SongArtists
CREATE INDEX IX_SongArtists_SongId ON SongArtists (SongId)
GO

DROP INDEX IF EXISTS IX_Songs_TrendId ON Songs
CREATE INDEX IX_Songs_TrendId ON Songs (TrendId)
GO

ALTER DATABASE SpotifyDataset
ADD FILEGROUP FILE1
ALTER DATABASE SpotifyDataset
ADD FILEGROUP FILE2
ALTER DATABASE SpotifyDataset
ADD FILEGROUP FILE3
ALTER DATABASE SpotifyDataset
ADD FILEGROUP FILE4
GO

ALTER DATABASE SpotifyDataset
ADD FILE
(
    NAME = FILE1,
    FILENAME = '/var/opt/mssql/data/FILE1.mdf',
    SIZE = 3072 KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 1024 KB
) TO FILEGROUP FILE1

ALTER DATABASE SpotifyDataset
ADD FILE
(
    NAME = FILE2,
    FILENAME = '/var/opt/mssql/data/FILE2.mdf',
    SIZE = 3072 KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 1024 KB
) TO FILEGROUP FILE2

ALTER DATABASE SpotifyDataset
ADD FILE
(
    NAME = FILE3,
    FILENAME = '/var/opt/mssql/data/FILE3.mdf',
    SIZE = 3072 KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 1024 KB
) TO FILEGROUP FILE3

ALTER DATABASE SpotifyDataset
ADD FILE
(
    NAME = FILE4,
    FILENAME = '/var/opt/mssql/data/FILE4.mdf',
    SIZE = 3072 KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 1024 KB
) TO FILEGROUP FILE4

CREATE PARTITION FUNCTION pf_Song_trends (INT)
AS RANGE LEFT FOR VALUES (5000000, 10000000, 20000000);
GO

CREATE PARTITION SCHEME ps_Song_trends
AS PARTITION pf_Song_trends
TO (FILE1, FILE2, FILE3, FILE4);
GO

ALTER TABLE SongArtists DROP CONSTRAINT fk_SongArtists_ArtistId_Songs;
ALTER TABLE Songs DROP CONSTRAINT PK__Songs__3214EC0754705CDE;
ALTER TABLE Songs ADD CONSTRAINT PK__Songs__3214EC0754705CDE PRIMARY KEY CLUSTERED
(
    Id
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
ON ps_Song_trends(Id)
GO

ALTER TABLE SongArtists ADD CONSTRAINT fk_SongArtists_ArtistId_Songs FOREIGN KEY (SongId) REFERENCES [SpotifyDataset].[dbo].Songs (Id)
GO
