import { JsonImporter } from "./json-importer.js";
import { DataSetCreator } from "./data-set-creator.js";
const userPath = 'dataset/USER_MOCK_DATA.json';
const productPath = 'dataset/PRODUCT_MOCK_DATA.json';
const groceryListPath = 'dataset/LIST_MOCK_DATA.json';
const userImporter = new JsonImporter();
const productImporter = new JsonImporter();
const groceryListImporter = new JsonImporter();
const users = await userImporter.getJSONData(userPath);
const products = await productImporter.getJSONData(productPath);
const groceryLists = await groceryListImporter.getJSONData(groceryListPath);
const creator = new DataSetCreator(products, users, groceryLists);
creator.create();
